project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('manager/', include('taskmanager.urls')),
]

taskmanager/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('connect/', connect, name = "Connexion"),
    path('disconnect/', disconnect, name = "Deconnexion"),
    path('projects/', projets, name = "Projets"),
    path('project/<int:id>', projet, name = "Projet"),
    path('task/<int:id>', tache, name = "Tache"),
    path('tasks/', taches, name = "Taches"),
    path('user/', utilisateur, name = "Utilisateur"),
    path('delete-project/<int:id>/', delete_projet, name = "Suppression Projet"),
    path('delete-project-def/<int:id>/', delete_def_projet, name = "Suppression Definitive Projet"),
    path('modify-project/<int:id>/', modify_projet, name = "Modification Projet"),
    path('add-project/', add_projet, name = "Ajout Projet"),
    path('delete-tache/<int:id>/', delete_tache, name = "Suppression Tache"),
    path('delete-tache-def/<int:id>/', delete_def_tache, name = "Suppression Definitive Tache"),
    path('modify-tache/<int:id>/', modify_tache, name = "Modification Tache"),
    path('add-tache/<int:id>/', add_tache, name = "Ajout Tache"),
    path('delete-comm/<int:id>/', delete_comm, name = "Suppression Commentaire"),
    path('delete-comm-def/<int:id>/', delete_def_comm, name = "Suppression Definitive Commentaire"),
    path('modify-comm/<int:id>/', modify_comm, name = "Modification Commentaire"),
    path('add-comm/<int:id>/', add_comm, name = "Ajout Commentaire"),
    path('denied/', denied, name = "Refusé"),
]

taskmanager/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

class Projet(models.Model):
    nom = models.CharField(max_length=100)

    class Meta:
        verbose_name = "projet"

    def __str__(self):
        return self.nom

class Statut(models.Model):
    nom = models.CharField(max_length=50)
    couleur = models.CharField(max_length=50)

    class Meta:
        verbose_name = "statut"

    def __str__(self):
        return self.nom

class Tache(models.Model):
    titre = models.CharField(max_length=100)
    description = models.TextField()
    start = models.DateField(default=timezone.now)
    end = models.DateField(default=timezone.now)
    priority = models.IntegerField(default=1)
    assigned = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.ForeignKey('Statut', on_delete=models.CASCADE)
    projet = models.ForeignKey('Projet', on_delete=models.CASCADE)

    class Meta:
        verbose_name = "tache"

    def __str__(self):
        return self.titre

class Commentaire(models.Model):
    texte = models.TextField()
    date = models.DateTimeField(default=timezone.now)
    tache = models.ForeignKey('Tache', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "commentaire"

    def __str__(self):
        return self.texte[:40]+"..."

taskmanager/forms.py
from django import forms
from .models import Projet, Tache, Commentaire, Statut
from django.contrib.auth.models import User
from django.utils import timezone

class DateInput(forms.DateInput):
    input_type = 'date'

class ConnectForm(forms.Form):
    utilisateur = forms.CharField(label="Nom d'Utilisateur")
    mdp = forms.CharField(label="Mot de Passe", widget=forms.PasswordInput())

class ModifyProjectForm(forms.ModelForm):
    class Meta:
        model=Projet
        fields="__all__"

class ModifyTacheForm(forms.ModelForm):
    class Meta:
        model=Tache
        fields="__all__"
        widgets = {
            'start': DateInput(),
            'end': DateInput()
        }

class ModifyCommentaireForm(forms.ModelForm):
    class Meta:
        model=Commentaire
        fields="__all__"

class NewTacheForm(forms.ModelForm):
    class Meta:
        model=Tache
        exclude = ('projet',)

class FilterTacheForm(forms.Form):
    assigned = forms.ModelChoiceField(queryset=User.objects.all(), label="Assigné à", required=False)
    status = forms.ModelChoiceField(queryset=Statut.objects.all(), label="Statut", required=False)
    comm_select = forms.CharField(label='Commencé', widget=forms.RadioSelect(choices=[
        ('avant', "Avant"),
        ('apres', "Après"),
    ]), )
    comm_date = forms.DateField(label='le', widget=DateInput(), required=False)
    term_select = forms.CharField(label='Terminé', widget=forms.RadioSelect(choices=[
        ('avant', "Avant"),
        ('apres', "Après"),
    ]))
    term_date = forms.DateField(label='le', widget=DateInput(), required=False)
    sort_by = forms.CharField(label='Trié par', widget=forms.Select(choices=[
        ('titre', "Nom"),
        ('assigned', "Assigné à"),
        ('priority', "Priorité"),
        ('status', "Statut"),
        ('start', "Date de début"),
        ('end', "Date de fin"),
    ]))
    sort_order = forms.CharField(label='dans l\'ordre', widget=forms.RadioSelect(choices=[
        ('croiss', "Croissant"),
        ('decroiss', "Decroissant"),
    ]))

taskmanager/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.utils import timezone
from django.contrib.auth.models import Permission
from .forms import *
from .models import *

# Create your views here.
def connect(request):
    connected = request.user.is_authenticated
    name = ""
    username = ""
    form = ConnectForm(request.POST or None)
    error = False
    if connected:
        name = request.user.first_name + " " + request.user.last_name
        username = request.user.username
        return redirect(utilisateur)
    else:
        if form.is_valid():
            error = True
            username = form.cleaned_data['utilisateur']
            password = form.cleaned_data['mdp']
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                return redirect(utilisateur)
            else:
                pass
    return render(request, 'taskmanager/connect.html', locals())

def disconnect(request):
    connected = request.user.is_authenticated
    if connected:
        logout(request)
    return redirect(connect)

def denied(request):
    connected = request.user.is_authenticated
    name = ""
    username = ""
    projets_list = None
    if connected:
        name = request.user.first_name + " " + request.user.last_name
        username = request.user.username
    return render(request, 'taskmanager/denied.html', locals())


def projets(request):
    connected = request.user.is_authenticated
    name = ""
    username = ""
    projets_list = []
    projets_taches_nbre = []
    projets = []
    if connected:
        name = request.user.first_name + " " + request.user.last_name
        username = request.user.username
        if request.user.has_perm('taskmanager.view_projet'):
            modify = request.user.has_perm('taskmanager.change_projet')
            add = request.user.has_perm('taskmanager.add_projet')
            delete = request.user.has_perm('taskmanager.delete_projet')
            projets_list = list(Projet.objects.all())
            for projet in projets_list:
                projets_taches_nbre.append(0)
                for tache in Tache.objects.all():
                    if tache.projet == projet:
                        projets_taches_nbre[-1]+=1
                projets.append([projet, projets_taches_nbre[-1]])
        else:
            return redirect(denied)
    else:
        return redirect(connect)
    return render(request, 'taskmanager/projects.html', locals())


def projet(request, id):
    connected = request.user.is_authenticated
    name = ""
    username = ""
    projet = None
    taches = None
    if connected:
        name = request.user.first_name + " " + request.user.last_name
        username = request.user.username
        modify_projet = request.user.has_perm('taskmanager.change_projet')
        modify_tache = request.user.has_perm('taskmanager.change_tache')
        add_tache = request.user.has_perm('taskmanager.add_tache')
        delete_tache = request.user.has_perm('taskmanager.delete_tache')
        if request.user.has_perm('taskmanager.view_projet') and request.user.has_perm('taskmanager.view_tache'):
            projet = Projet.objects.get(id=id)
            form = FilterTacheForm(request.POST or None, initial={'comm_select': 'avant', 'term_select': 'avant', 'sort_order': 'croiss'})
            if form.is_valid():
                taches = Tache.objects.filter(projet = projet)
                if form.cleaned_data['assigned'] is not None:
                    taches = taches.filter(assigned=form.cleaned_data['assigned'])
                if form.cleaned_data['status'] is not None:
                    taches = taches.filter(status=form.cleaned_data['status'])
                if form.cleaned_data['comm_date'] is not None:
                    if form.cleaned_data['comm_select'] == "avant":
                        taches = taches.filter(start__lte=form.cleaned_data['comm_date'])
                    else:
                        taches = taches.filter(start__gte=form.cleaned_data['comm_date'])
                if form.cleaned_data['term_date'] is not None:
                    if form.cleaned_data['term_select'] == "avant":
                        taches = taches.filter(end__lte=form.cleaned_data['term_date'])
                    else:
                        taches = taches.filter(end__gte=form.cleaned_data['term_date'])
                if form.cleaned_data['sort_by'] != "":
                    if form.cleaned_data['sort_order'] == "decroiss":
                        taches = taches.order_by("-{}".format(form.cleaned_data['sort_by']))
                    else:
                        taches = taches.order_by("{}".format(form.cleaned_data['sort_by']))
            else:
                taches = Tache.objects.filter(projet = projet)
            projet = Projet.objects.get(id=id)
        else:
            return redirect(denied)
    else:
        return redirect(connect)
    return render(request, 'taskmanager/projet.html', locals())

def tache(request, id):
    connected = request.user.is_authenticated
    name = ""
    username = ""
    tache = None
    commentaires = None
    if connected:
        name = request.user.first_name + " " + request.user.last_name
        username = request.user.username
        if request.user.has_perm('taskmanager.view_tache'):
            modify = request.user.has_perm('taskmanager.change_tache')
            view_comments = request.user.has_perm('taskmanager.view_commentaire')
            add_comment = request.user.has_perm('taskmanager.add_commentaire')
            modify_comment = request.user.has_perm('taskmanager.change_commentaire')
            delete_comment = request.user.has_perm('taskmanager.delete_commentaire')
            tache = Tache.objects.get(id=id)
            commentaires = Commentaire.objects.filter(tache = tache).order_by('date')
        else:
            return redirect(denied)
    else:
        return redirect(connect)
    return render(request, 'taskmanager/tache.html', locals())


def taches(request):
    connected = request.user.is_authenticated
    name = ""
    username = ""
    if connected:
        name = request.user.first_name + " " + request.user.last_name
        username = request.user.username
        if request.user.has_perm('taskmanager.view_tache'):
            modify_tache = request.user.has_perm('taskmanager.change_tache')
            delete_tache = request.user.has_perm('taskmanager.delete_tache')
            form = FilterTacheForm(request.POST or None, initial={'comm_select':'avant', 'term_select':'avant', 'sort_order':'croiss'})
            if form.is_valid():
                taches = Tache.objects.all()
                if form.cleaned_data['assigned'] is not None:
                    taches = taches.filter(assigned=form.cleaned_data['assigned'])
                if form.cleaned_data['status'] is not None:
                    taches = taches.filter(status=form.cleaned_data['status'])
                if form.cleaned_data['comm_date'] is not None:
                    if form.cleaned_data['comm_select'] == "avant":
                        taches = taches.filter(start__lte=form.cleaned_data['comm_date'])
                    else:
                        taches = taches.filter(start__gte=form.cleaned_data['comm_date'])
                if form.cleaned_data['term_date'] is not None:
                    if form.cleaned_data['term_select'] == "avant":
                        taches = taches.filter(end__lte=form.cleaned_data['term_date'])
                    else:
                        taches = taches.filter(end__gte=form.cleaned_data['term_date'])
                if form.cleaned_data['sort_by'] != "":
                    if form.cleaned_data['sort_order'] == "decroiss":
                        taches = taches.order_by("-{}".format(form.cleaned_data['sort_by']))
                    else:
                        taches = taches.order_by("{}".format(form.cleaned_data['sort_by']))
            else:
                taches = Tache.objects.all()
            return render(request, "taskmanager/taches.html", locals())
        else:
            return redirect(denied)
    else:
        return redirect(connect)

def utilisateur(request):
    connected = request.user.is_authenticated
    name = ""
    username = ""
    if connected:
        name = request.user.first_name + " " + request.user.last_name
        username = request.user.username

        groups = request.user.groups.all()
        permissions = Permission.objects.filter(user=request.user)
        taches = Tache.objects.filter(assigned=request.user)
        projects = []
        for tache in taches:
            if tache.projet not in projects:
                projects.append(tache.projet)
        return render(request, "taskmanager/user.html", locals())
    else:
        return redirect(connect)

def delete_projet(request, id):
    connected = request.user.is_authenticated
    name = ""
    username = ""
    tache = None
    commentaires = None
    if connected:
        name = request.user.first_name + " " + request.user.last_name
        username = request.user.username
        if request.user.has_perm('taskmanager.delete_projet'):
            project = Projet.objects.get(id=id)
            return render(request, "taskmanager/delete_project.html", locals())
        else:
            return redirect(denied)
    else:
        return redirect(connect)

def delete_def_projet(request, id):
    if request.user.is_authenticated:
        if request.user.has_perm('taskmanager.delete_projet'):
            Projet.objects.get(id=id).delete()
            return redirect(projets)
        else:
            return redirect(denied)
    else:
        return redirect(connect)

def modify_projet(request, id):
    connected = request.user.is_authenticated
    name = ""
    username = ""
    tache = None
    commentaires = None

templates/taskmanager/add_project.html
{% extends "base.html" %}

{% block titre %}Ajout d'un projet{% endblock %}

{% load static %}

{% block css %}<link rel="stylesheet" href="{% static 'css/taskmanager/modify.css' %} ">{% endblock %}

{% block contenu %}
    <h3>Ajout d'un projet</h3>
    <div id="form-cont">
        <form action="{% url "Ajout Projet" %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="button-holder center"><input class="button" type="submit" value="Ajouter"></div>
        </form>
        <div class="button-holder center"><a href="{% url "Projets" %}" class="link"><button class="button">Retour</button></a></div>
    </div>
{% endblock %}

templates/taskmanager/add_tache.html
{% extends "base.html" %}

{% block titre %}Ajout d'une tache{% endblock %}

{% load static %}

{% block css %}<link rel="stylesheet" href="{% static 'css/taskmanager/modify.css' %} ">{% endblock %}

{% block contenu %}
    <h3>Ajout d'une Tache à {{ proj.nom }}</h3>
    <div id="form-cont">
        <form action="{% url "Ajout Tache" proj.id%}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <p><label for="id_projet">Projet:</label> <select id="id_projet" disabled>
                <option selected="">{{ proj.nom }}</option>
            </select></p>
            <div class="button-holder center"><input class="button" type="submit" value="Ajouter"></div>
        </form>
        <script>
            document.getElementById("id_projet").setAttribute("disabled", "true");
            document.getElementById("id_start").setAttribute("type", "date");
            document.getElementById("id_end").setAttribute("type", "date");
        </script>
        <div class="button-holder center"><a href="{% url "Projet" proj.id %}" class="link"><button class="button">Retour</button></a></div>
    </div>
{% endblock %}

templates/taskmanager/connect.html
{% extends "base.html" %}

{% block titre %}Connect{% endblock %}

{% load static %}

{% block css %}<link rel="stylesheet" href="{% static 'css/taskmanager/connect.css' %} ">{% endblock %}

{% block contenu %}
    {% if error %}
        <p id="error">Nom d'utilisateur ou mot de passe non reconnu</p>
    {% endif %}
    <div class="major">
        <form action="" method="post" id = "connect-form">
            {% csrf_token %}
            {{ form.as_p }}
            <input id="connect" type = "submit" value = "Se connecter">
        </form>
    </div>
{% endblock %}

templates/taskmanager/delete_commentaire.html
{% extends "base.html" %}

{% block titre %}Suppression ?{% endblock %}

{% load static %}

{% block css %}<link rel="stylesheet" href="{% static 'css/taskmanager/delete.css' %} ">{% endblock %}

{% block contenu %}
    <h4 id="delete">Vous êtes sur le point de supprimmer un commentaire</h4>
    <h4 id="sure">Etes-vous sur ?</h4>
    <table id="results">
        <tr>
            <td><a href="{% url "Suppression Definitive Commentaire" comm.id %}"><button class="res">Oui</button></a></td>
        </tr>
        <tr>
            <td><a href="{% url "Tache" comm.tache.id %}"><button class="res">Non</button></a></td>
        </tr>
    </table>
{% endblock %}

templates/taskmanager/delete_tache.html
{% extends "base.html" %}

{% block titre %}Suppression ?{% endblock %}

{% load static %}

{% block css %}<link rel="stylesheet" href="{% static 'css/taskmanager/delete.css' %} ">{% endblock %}

{% block contenu %}
    <h4 id="delete">Vous êtes sur le point de supprimmer la tache {{ task.titre }}</h4>
    <h4 id="sure">Etes-vous sur ?</h4>
    <table id="results">
        <tr>
            <td><a href="{% url "Suppression Definitive Tache" task.id %}"><button class="res">Oui</button></a></td>
        </tr>
        <tr>
            <td><a href="{% url "Projet" task.projet.id %}"><button class="res">Non</button></a></td>
        </tr>
    </table>
{% endblock %}

templates/taskmanager/denied.html
{% extends "base.html" %}

{% block titre %}Refusé{% endblock %}

{% load static %}

{% block css %}<link rel="stylesheet" href="{% static 'css/taskmanager/denied.css' %} ">{% endblock %}

{% block contenu %}
    <h3>Vos permissions ne vous permettent pas d'acceder à cette page...</h3>
{% endblock %}

templates/taskmanager/modify_commentaire.html
{% extends "base.html" %}

{% block titre %}Modification d'un commentaire{% endblock %}

{% load static %}

{% block css %}<link rel="stylesheet" href="{% static 'css/taskmanager/modify.css' %}">{% endblock %}

{% block contenu %}
    <h3>Modification d'un commentaire</h3>
    <div id="form-cont">
        <form action="{% url "Modification Commentaire" comm.id %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="button-holder center"><input class="button" type="submit" value="Modifier"></div>
        </form>
        <div class="button-holder center"><a href="{% url "Tache" comm.tache.id %}" class="link"><button class="button">Retour</button></a></div>
    </div>
{% endblock %}

templates/taskmanager/modify_project.html
{% extends "base.html" %}

{% block titre %}Modification de {{ proj.nom }}{% endblock %}

{% load static %}

{% block css %}<link rel="stylesheet" href="{% static 'css/taskmanager/modify.css' %} ">{% endblock %}

{% block contenu %}
    <h3>Modification du projet {{ proj.nom }}</h3>
    <div id="form-cont">
        <form action="{% url "Modification Projet" proj.id %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input id="apply" type="submit" value="Modifier">
        </form>
        <a href="{% url "Projets" %}"><button id="retour">Retour</button></a>
    </div>
{% endblock %}

templates/taskmanager/modify_tache.html
{% extends "base.html" %}

{% block titre %}Modification de {{ task.titre }}{% endblock %}

{% load static %}

{% block css %}<link rel="stylesheet" href="{% static 'css/taskmanager/modify.css' %}">{% endblock %}

{% block contenu %}
    <h3>Modification de la tache {{ task.titre }}</h3>
    <div id="form-cont">
        <form action="{% url "Modification Tache" task.id %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="button-holder center"><input class="button" type="submit" value="Modifier"></div>
        </form>
        <div class="button-holder center"><a href="{% url "Tache" task.id %}" class="link"><button class="button">Retour</button></a></div>
    </div>
{% endblock %}

templates/taskmanager/projects.html
{% extends "base.html" %}

{% block titre %}Projets{% endblock %}

{% load static %}

{% block css %}<link rel="stylesheet" href="{% static 'css/taskmanager/projets.css' %} ">{% endblock %}

{% block contenu %}
    <ul>
    {% for projet in projets %}
        <a class = "links" href="{% url "Projet" projet.0.id %}">
            <li>
                <table class="projet">
                    <tr>
                        <td>
                            <h3>
                                {% if delete %}
                                    <a href="{% url "Suppression Projet" projet.0.id %}"><img src="{% static "images/del.png" %}" alt="del" width = "18px"/></a>
                                {% endif %}
                                {% if modify %}
                                    <a href="{% url "Modification Projet" projet.0.id %}"><img src="{% static "images/mod.png" %}" alt="mod" width = "18px"/></a>
                                {% endif %}
                                {{ projet.0.nom }}
                            </h3>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <h5>{{ projet.1 }} tache{{ projet.1|pluralize }} listée{{ projet.1|pluralize }} dans ce projet</h5>
                        </td>
                    </tr>
                </table>
            </li>
        </a>
    {% endfor %}
    </ul>
    {% if add %}
        <div class="center-pin">
            <a href="{% url "Ajout Projet" %}"><img src="{% static "images/add.png" %}" alt="add" width = "18px"/></a>
        </div>
    {% endif %}

{% endblock %}

templates/taskmanager/projet.html
{% extends "base.html" %}

{% block titre %}Projet {{ projet.nom }}{% endblock %}

{% load static %}

{% block css %}<link rel="stylesheet" href="{% static 'css/taskmanager/projet.css' %} ">{% endblock %}

{% block contenu %}
    <h3>
        {% if modify_projet %}
            <a href="{% url "Modification Projet" projet.id %}"><img src="{% static "images/mod.png" %}" alt="mod" width = "18px"/></a>
        {% endif %}
        {{ projet.nom }}
    </h3>
    <h4 id="subtitle">Taches</h4>
    <div class="bloc-40">
        <form action = "{% url "Projet" projet.id %}" method="post">
            {% csrf_token %}
            {{ form.as_ul }}
            <input class="filter" type="submit" value="Filtrer">
        </form>
        <a href="{% url "Projet" projet.id %}"><button class="filter">Annuler</button></a>
    </div>
    <ul id="content">
        {% for tache in taches %}
            <li>
                <a href="{% url "Tache" tache.id %}">
                    <table>
                        <tr>
                           <td colspan="4" >
                               <h2>
                                    {% if delete_tache %}
                                        <a href="{% url "Suppression Tache" tache.id %}"><img src="{% static "images/del.png" %}" alt="del" width = "18px"/></a>
                                    {% endif %}
                                    {% if modify_tache %}
                                        <a href="{% url "Modification Tache" tache.id %}"><img src="{% static "images/mod.png" %}" alt="mod" width = "18px"/></a>
                                    {% endif %}
                                   {{ tache.titre }}
                               </h2>
                           </td>
                           <td rowspan="2" >
                               <div class="stat">
                                    <h4 class="size-stat" style="background-color:{{ tache.status.couleur }};" >{{ tache.status.nom }}</h4>
                               </div>
                           </td>
                        </tr>
                        <tr>
                           <td class="mini">
                                <p>Priorité : {{ tache.priority }}</p>
                           </td>
                           <td class="mini">
                                <p>Assigné à : {{ tache.assigned }}</p>
                           </td>
                           <td class="mini">
                                <p>Commencée le : {{ tache.start }}</p>
                           </td>
                           <td class="mini">
                                <p>Terminée le : {{ tache.end }}</p>
                           </td>
                        </tr>
                    </table>
                </a>
            </li>
        {% endfor %}
    </ul>
    {% if add_tache %}
        <div class="center-pin">
            <a href="{% url "Ajout Tache" projet.id %}"><img src="{% static "images/add.png" %}" alt="add" width = "18px"/></a>
        </div>
    {% endif %}
    <a id="ret" href="{% url "Projets" %}"><p>Retour</p></a>
{% endblock %}

templates/taskmanager/tache.html
{% extends "base.html" %}

{% block titre %}Tache {{ tache.titre }}{% endblock %}

{% load static %}

{% block css %}<link rel="stylesheet" href="{% static 'css/taskmanager/tache.css' %} ">{% endblock %}

{% block contenu %}
    <h3>
        {% if modify %}
            <a href="{% url "Modification Tache" tache.id %}"><img src="{% static "images/mod.png" %}" alt="mod" width = "18px"/></a>
        {% endif %}
        {{ tache.titre }}
    </h3>
    <table class="content">
        <tr>
            <td colspan="2">
                <h5>{{ tache.description|linebreaks }}</h5>
            </td>
            <td>
                <div class="stat">
                    <h4 class="size-stat" style="background-color:{{ tache.status.couleur }};" >{{ tache.status }}</h4>
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <p>Commence le {{ tache.start }}</p>
            </td>
            <td>
                <p>Finit le {{ tache.end }}</p>
            </td>
            <td>
                <p>Priorité : {{ tache.priority }}</p>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <h5>Projet : {{ tache.projet }}</h5>
            </td>
            <td>
                <p>Assigné à : {{ tache.assigned }}</p>
            </td>
        </tr>
    </table>
    {% if view_comments %}
        <h4 id="subtitle">Commentaires</h4>
        <ul id="comments">
            {% for comm in commentaires %}
                <li>
                    <table>
                        <tr>
                            <td>
                                <p class="comm-header">
                                    {% if delete_comment %}
                                        <a href="{% url "Suppression Commentaire" comm.id %}"><img src="{% static "images/del.png" %}" alt="del" width = "18px"/></a>
                                    {% endif %}
                                    {% if modify_comment %}
                                        <a href="{% url "Modification Commentaire" comm.id %}"><img src="{% static "images/mod.png" %}" alt="mod" width = "18px"/></a>
                                    {% endif %}
                                    par {{ comm.user }} le {{ comm.date }}
                                </p>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <p class="comm">{{ comm.texte }}</p>
                            </td>
                        </tr>
                    </table>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <h4 id="subtitle">Commentaires non visibles</h4>
    {% endif %}
    {% if add_comment %}
        <form action="{% url "Ajout Commentaire" tache.id %}" method="post">
            {% csrf_token %}
            <table id="new-comment">
                <tr>
                    <td>
                        <textarea id="text" name="text"></textarea>
                    </td>
                </tr>
                <tr>
                    <td class="centered-cell">
                        <input type="submit" value="Envoyer" id="send-comm">
                    </td>
                </tr>
            </table>
        </form>
    {% endif %}
    <a id="ret" href="{% url "Projet" tache.projet.id %}"><p>Retour</p></a>
{% endblock %}